In [1]:
import pandas as pd

In [2]:
df_calls = pd.read_csv('../MNPD_Calls/Metro_Nashville_Police_Department_Calls_for_Service.csv', low_memory=False)
df_calls

,Event Number,Call Received,Complaint Number,Tencode,Tencode Description,Tencode Suffix,Tencode Suffix Description,Disposition Code,Disposition Description,Block,Street Name,Unit Dispatched,Shift,Sector,Zone,RPA,Latitude,Longitude,Mapped Location
0,PD201400831493,08/11/2014 12:27:41 AM,NaN,93,TRAFFIC VIOLATION,NaN,NaN,9T,NaN,NaN,1188 CINDER RD,523C,C,525,NaN,NaN,NaN,NaN,NaN
1,PD201400733929,07/13/2014 09:06:57 AM,2.014066e+10,50,THEFT,RV,NaN,1,M.P.D. REPORT COMPLED,NaN,NaN,715A,A,NaN,NaN,NaN,NaN,NaN,NaN
2,PD201400403153,04/17/2014 04:03:00 PM,2.014037e+10,57,FIGHT / ASSAULT,RJ,NaN,1,M.P.D. REPORT COMPLED,NaN,NaN,711B,B,NaN,NaN,NaN,NaN,NaN,NaN
3,PD201400035391,01/09/2014 11:10:00 PM,2.014003e+10,50,THEFT,R,REPORT,1,M.P.D. REPORT COMPLED,NaN,NaN,335C,C,NaN,NaN,NaN,NaN,NaN,NaN
4,PD201401100405,10/24/2014 12:58:19 PM,2.014098e+10,50,THEFT,RC,NaN,1C,NaN,NaN,NaN,HAPR,A,NaN,NaN,NaN,NaN,NaN,NaN
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
7365087,PD202100501662,08/06/2021 08:31:12 PM,NaN,95,MEAL BREAK,NaN,NaN,4,ASSISTED CITIZEN,NaN,NaN,854B,B,MT,811,5711.0,NaN,NaN,NaN
7365088,PD202100340556,05/26/2021 07:56:57 AM,NaN,15,COMMUNITY POLICING ACTIVITY,P,PROGRESS,15,COMMUNITY POLICING,NaN,NaN,2911,A,N,611,4425.0,NaN,NaN,NaN
7365089,PD202100370448,06/08/2021 02:18:06 PM,2.021031e+10,50,THEFT,R,REPORT,1,M.P.D. REPORT COMPLED,NaN,NaN,MAPR1,A,NaN,NaN,NaN,NaN,NaN,NaN
7365090,PD202100266286,04/24/2021 12:02:07 AM,2.021023e+10,45,VEHICLE ACCIDENT - PROPERTY DAMAGE,P,PROGRESS,6,ASSISTED OTHER UNIT,NaN,NaN,325C,C,S,313,8351.0,NaN,NaN,NaN
7365091,PD202100433235,07/06/2021 06:08:19 AM,NaN,8000,EXPLOSION,NaN,NaN,4,ASSISTED CITIZEN,NaN,NaN,510C,A,H,515,9315.0,NaN,NaN,NaN

In [3]:
df_calls.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 7365092 entries, 0 to 7365091
Data columns (total 19 columns):
 #   Column                      Dtype
---  ------                      -----
 0   Event Number                object
 1   Call Received               object
 2   Complaint Number            float64
 3   Tencode                     int64
 4   Tencode Description         object
 5   Tencode Suffix              object
 6   Tencode Suffix Description  object
 7   Disposition Code            object
 8   Disposition Description     object
 9   Block                       float64
 10  Street Name                 object
 11  Unit Dispatched             object
 12  Shift                       object
 13  Sector                      object
 14  Zone                        object
 15  RPA                         float64
 16  Latitude                    float64
 17  Longitude                   float64
 18  Mapped Location             object
dtypes: float64(5), int64(1), object(13)
memory usage: 1.0+ GB

In [4]:
df_calls.isnull().sum()

Event Number                        0
Call Received                       0
Complaint Number              6774350
Tencode                             0
Tencode Description            167608
Tencode Suffix                3135394
Tencode Suffix Description    3696550
Disposition Code                34954
Disposition Description       1757290
Block                         5485613
Street Name                   4841421
Unit Dispatched                465554
Shift                               0
Sector                        1493099
Zone                           845601
RPA                           1439844
Latitude                      6172346
Longitude                     6172346
Mapped Location               6172346
dtype: int64

In [5]:
df_calls['Event Number'].is_unique

False

In [6]:
df_calls['Event Number'].value_counts()

PD201400978620    7
PD201401134789    7
PD201401105385    6
PD201401288910    6
PD201400978623    6
                 ..
PD202000232454    1
PD201700709264    1
PD201700937400    1
PD202000909717    1
PD201800174704    1
Name: Event Number, Length: 7362103, dtype: int64

In [16]:
df_calls[df_calls['Event Number'] == 'PD201401105385']

,Event Number,Call Received,Complaint Number,Tencode,Tencode Description,Tencode Suffix,Tencode Suffix Description,Disposition Code,Disposition Description,Block,Street Name,Unit Dispatched,Shift,Sector,Zone,RPA,Latitude,Longitude,Mapped Location
1399893,PD201401105385,10/25/2014 09:29:54 PM,NaN,43,WANT OFFICER FOR INVESTIGATION / ASSISTA,P,PROGRESS,NaN,NaN,700.0,MCMURRAY DR,NaN,B,NaN,316X,0.0,36.055,-86.742,POINT (-86.742 36.055)
1402068,PD201401105385,10/25/2014 09:29:54 PM,NaN,43,WANT OFFICER FOR INVESTIGATION / ASSISTA,P,PROGRESS,NaN,NaN,700.0,MCMURRAY DR,NaN,B,NaN,316X,0.0,36.055,-86.742,POINT (-86.742 36.055)
1406890,PD201401105385,10/25/2014 09:29:54 PM,NaN,43,WANT OFFICER FOR INVESTIGATION / ASSISTA,P,PROGRESS,NaN,NaN,700.0,MCMURRAY DR,NaN,B,NaN,316X,0.0,36.055,-86.742,POINT (-86.742 36.055)
1410927,PD201401105385,10/25/2014 09:29:54 PM,NaN,43,WANT OFFICER FOR INVESTIGATION / ASSISTA,P,PROGRESS,9,SUBJECT WARNED,700.0,MCMURRAY DR,832B,B,NaN,316X,0.0,36.055,-86.742,POINT (-86.742 36.055)
1414768,PD201401105385,10/25/2014 09:29:54 PM,NaN,43,WANT OFFICER FOR INVESTIGATION / ASSISTA,P,PROGRESS,NaN,NaN,700.0,MCMURRAY DR,NaN,B,NaN,316X,0.0,36.055,-86.742,POINT (-86.742 36.055)
1419536,PD201401105385,10/25/2014 09:29:54 PM,NaN,43,WANT OFFICER FOR INVESTIGATION / ASSISTA,P,PROGRESS,NaN,NaN,700.0,MCMURRAY DR,NaN,B,NaN,316X,0.0,36.055,-86.742,POINT (-86.742 36.055)

In [8]:
df_calls['Call Received'].value_counts()

10/01/2020 06:26:06 PM    25
03/01/2018 10:52:13 AM    25
08/05/2019 10:17:32 AM    24
01/03/2019 09:58:02 AM    24
06/12/2018 06:31:27 PM    24
                          ..
12/06/2019 06:23:01 AM     1
10/05/2015 02:02:05 PM     1
09/08/2014 03:18:43 PM     1
10/23/2015 12:01:18 PM     1
05/27/2017 12:41:18 AM     1
Name: Call Received, Length: 7228925, dtype: int64

In [11]:
df_calls[df_calls['Call Received'] == '08/05/2019 10:17:32 AM']

,Event Number,Call Received,Complaint Number,Tencode,Tencode Description,Tencode Suffix,Tencode Suffix Description,Disposition Code,Disposition Description,Block,Street Name,Unit Dispatched,Shift,Sector,Zone,RPA,Latitude,Longitude,Mapped Location
4262202,PD201900677119,08/05/2019 10:17:32 AM,NaN,43,WANT OFFICER FOR INVESTIGATION / ASSISTA,R,REPORT,1,M.P.D. REPORT COMPLED,NaN,NaN,PROB,A,S,315,8801.0,NaN,NaN,NaN
4262471,PD201900677128,08/05/2019 10:17:32 AM,NaN,43,WANT OFFICER FOR INVESTIGATION / ASSISTA,R,REPORT,1,M.P.D. REPORT COMPLED,NaN,NaN,PROB,A,S,315,8801.0,NaN,NaN,NaN
4264532,PD201900677125,08/05/2019 10:17:32 AM,NaN,43,WANT OFFICER FOR INVESTIGATION / ASSISTA,R,REPORT,1,M.P.D. REPORT COMPLED,NaN,NaN,PROB,A,S,315,8801.0,NaN,NaN,NaN
4264757,PD201900677122,08/05/2019 10:17:32 AM,NaN,43,WANT OFFICER FOR INVESTIGATION / ASSISTA,R,REPORT,1,M.P.D. REPORT COMPLED,NaN,NaN,PROB,A,S,315,8801.0,NaN,NaN,NaN
4266462,PD201900677132,08/05/2019 10:17:32 AM,NaN,43,WANT OFFICER FOR INVESTIGATION / ASSISTA,R,REPORT,1,M.P.D. REPORT COMPLED,NaN,NaN,PROB,A,S,315,8801.0,NaN,NaN,NaN
4267709,PD201900677133,08/05/2019 10:17:32 AM,NaN,43,WANT OFFICER FOR INVESTIGATION / ASSISTA,R,REPORT,1,M.P.D. REPORT COMPLED,NaN,NaN,PROB,A,S,315,8801.0,NaN,NaN,NaN
4269091,PD201900677140,08/05/2019 10:17:32 AM,NaN,43,WANT OFFICER FOR INVESTIGATION / ASSISTA,R,REPORT,1,M.P.D. REPORT COMPLED,NaN,NaN,PROB,A,S,315,8801.0,NaN,NaN,NaN
4269458,PD201900677139,08/05/2019 10:17:32 AM,NaN,43,WANT OFFICER FOR INVESTIGATION / ASSISTA,R,REPORT,1,M.P.D. REPORT COMPLED,NaN,NaN,PROB,A,S,315,8801.0,NaN,NaN,NaN
4269995,PD201900677129,08/05/2019 10:17:32 AM,NaN,43,WANT OFFICER FOR INVESTIGATION / ASSISTA,R,REPORT,1,M.P.D. REPORT COMPLED,NaN,NaN,PROB,A,S,315,8801.0,NaN,NaN,NaN
4270675,PD201900677138,08/05/2019 10:17:32 AM,NaN,43,WANT OFFICER FOR INVESTIGATION / ASSISTA,R,REPORT,1,M.P.D. REPORT COMPLED,NaN,NaN,PROB,A,S,315,8801.0,NaN,NaN,NaN
4272626,PD201900677121,08/05/2019 10:17:32 AM,NaN,43,WANT OFFICER FOR INVESTIGATION / ASSISTA,R,REPORT,1,M.P.D. REPORT COMPLED,NaN,NaN,PROB,A,S,315,8801.0,NaN,NaN,NaN
4274440,PD201900677130,08/05/2019 10:17:32 AM,NaN,43,WANT OFFICER FOR INVESTIGATION / ASSISTA,R,REPORT,1,M.P.D. REPORT COMPLED,NaN,NaN,PROB,A,S,315,8801.0,NaN,NaN,NaN
4275381,PD201900677134,08/05/2019 10:17:32 AM,NaN,43,WANT OFFICER FOR INVESTIGATION / ASSISTA,R,REPORT,1,M.P.D. REPORT COMPLED,NaN,NaN,PROB,A,S,315,8801.0,NaN,NaN,NaN
4276276,PD201900677124,08/05/2019 10:17:32 AM,NaN,43,WANT OFFICER FOR INVESTIGATION / ASSISTA,R,REPORT,1,M.P.D. REPORT COMPLED,NaN,NaN,PROB,A,S,315,8801.0,NaN,NaN,NaN
4276700,PD201900677123,08/05/2019 10:17:32 AM,NaN,43,WANT OFFICER FOR INVESTIGATION / ASSISTA,R,REPORT,1,M.P.D. REPORT COMPLED,NaN,NaN,PROB,A,S,315,8801.0,NaN,NaN,NaN
4278407,PD201900677127,08/05/2019 10:17:32 AM,NaN,43,WANT OFFICER FOR INVESTIGATION / ASSISTA,R,REPORT,1,M.P.D. REPORT COMPLED,NaN,NaN,PROB,A,S,315,8801.0,NaN,NaN,NaN
4278553,PD201900677120,08/05/2019 10:17:32 AM,NaN,43,WANT OFFICER FOR INVESTIGATION / ASSISTA,R,REPORT,1,M.P.D. REPORT COMPLED,NaN,NaN,PROB,A,S,315,8801.0,NaN,NaN,NaN
4279394,PD201900677137,08/05/2019 10:17:32 AM,NaN,43,WANT OFFICER FOR INVESTIGATION / ASSISTA,R,REPORT,1,M.P.D. REPORT COMPLED,NaN,NaN,PROB,A,S,315,8801.0,NaN,NaN,NaN
4279690,PD201900677142,08/05/2019 10:17:32 AM,NaN,43,WANT OFFICER FOR INVESTIGATION / ASSISTA,R,REPORT,1,M.P.D. REPORT COMPLED,NaN,NaN,PROB,A,S,315,8801.0,NaN,NaN,NaN
4281511,PD201900677135,08/05/2019 10:17:32 AM,NaN,43,WANT OFFICER FOR INVESTIGATION / ASSISTA,R,REPORT,1,M.P.D. REPORT COMPLED,NaN,NaN,PROB,A,S,315,8801.0,NaN,NaN,NaN
4284432,PD201900677136,08/05/2019 10:17:32 AM,NaN,43,WANT OFFICER FOR INVESTIGATION / ASSISTA,R,REPORT,1,M.P.D. REPORT COMPLED,NaN,NaN,PROB,A,S,315,8801.0,NaN,NaN,NaN
4284830,PD201900677141,08/05/2019 10:17:32 AM,NaN,43,WANT OFFICER FOR INVESTIGATION / ASSISTA,R,REPORT,1,M.P.D. REPORT COMPLED,NaN,NaN,PROB,A,S,315,8801.0,NaN,NaN,NaN
4285109,PD201900677126,08/05/2019 10:17:32 AM,NaN,43,WANT OFFICER FOR INVESTIGATION / ASSISTA,R,REPORT,1,M.P.D. REPORT COMPLED,NaN,NaN,PROB,A,S,315,8801.0,NaN,NaN,NaN
4286298,PD201900677131,08/05/2019 10:17:32 AM,NaN,43,WANT OFFICER FOR INVESTIGATION / ASSISTA,R,REPORT,1,M.P.D. REPORT COMPLED,NaN,NaN,PROB,A,S,315,8801.0,NaN,NaN,NaN

In [17]:
df_mapped = df_calls[~df_calls['Latitude'].isnull()]
df_mapped

,Event Number,Call Received,Complaint Number,Tencode,Tencode Description,Tencode Suffix,Tencode Suffix Description,Disposition Code,Disposition Description,Block,Street Name,Unit Dispatched,Shift,Sector,Zone,RPA,Latitude,Longitude,Mapped Location
1334,PD201400929894,09/07/2014 07:15:46 PM,NaN,3,NaN,NaN,NaN,4,ASSISTED CITIZEN,2400.0,BUENA VISTA PKE,4F70,B,NaN,231V,0.0,36.200,-86.825,POINT (-86.825 36.2)
1692,PD201800231514,03/04/2018 09:24:47 PM,NaN,93,TRAFFIC VIOLATION,NaN,NaN,9T,NaN,2500.0,MURFREESBORO PKE,5914,B,NaN,325T,0.0,36.076,-86.640,POINT (-86.64 36.076)
2460,PD201900702994,08/13/2019 01:52:06 PM,NaN,93,TRAFFIC VIOLATION,NaN,NaN,9T,NaN,700.0,MYATT DR,7F73,A,715,727,1731.0,36.294,-86.697,POINT (-86.697 36.294)
2488,PD201500290544,03/19/2015 04:50:16 AM,NaN,93,TRAFFIC VIOLATION,NaN,NaN,9T,NaN,300.0,HARDING PL,317C,C,NaN,313V,0.0,36.083,-86.711,POINT (-86.711 36.083)
2491,PD201500224343,03/01/2015 08:59:26 AM,NaN,96,BUSINESS CHECK,NaN,NaN,NaN,NaN,3700.0,MURFREESBORO PKE,333A,A,NaN,327X,0.0,36.043,-86.607,POINT (-86.607 36.043)
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
7345540,PD202100262831,04/22/2021 03:45:05 PM,2.021023e+10,57,FIGHT / ASSAULT,P,PROGRESS,11,DISREGARD / SIGNAL 9,5300.0,FREDERICKSBURG WAY W,820B,B,NaN,833,8621.0,36.033,-86.765,POINT (-86.765 36.033)
7353023,PD202100283691,05/01/2021 04:09:46 PM,NaN,43,WANT OFFICER FOR INVESTIGATION / ASSISTA,P,PROGRESS,11,DISREGARD / SIGNAL 9,5300.0,FREDERICKSBURG WAY W,NaN,B,NaN,833,8621.0,36.033,-86.765,POINT (-86.765 36.033)
7354147,PD202100492664,08/02/2021 05:41:24 PM,NaN,45,VEHICLE ACCIDENT - PROPERTY DAMAGE,P,PROGRESS,1,M.P.D. REPORT COMPLED,700.0,GALLATIN PIKE N,220B,B,Madiso,723,1761.0,36.271,-86.711,POINT (-86.711 36.271)
7356637,PD202100283693,05/01/2021 04:10:12 PM,NaN,43,WANT OFFICER FOR INVESTIGATION / ASSISTA,PM,NaN,4,ASSISTED CITIZEN,5300.0,FREDERICKSBURG WAY W,821B,B,NaN,833,8621.0,36.033,-86.765,POINT (-86.765 36.033)
7357487,PD202100465614,07/21/2021 10:42:20 AM,NaN,50,THEFT,TV,NaN,10,NO RESPONSE,NaN,NaN,525B,A,H,525,9611.0,36.266,-86.663,POINT (-86.663 36.266)